[package]
name = "psy-updater"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "psy-updater"
path = "src/main.rs"
[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
minisign-verify = "0.2"
anyhow = "1"
