[package]
name = "psy-netd"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "psy-netd"
path = "src/main.rs"
[dependencies]
psy-core = { path = "../../lib/psy-core" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
