[package]
name = "psychy-browser"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "psychy-browser"
path = "src/main.rs"
[dependencies]
psy-core   = { path = "../../lib/psy-core" }
psy-ui     = { path = "../../lib/psy-ui" }
gtk4       = "0.10"
libadwaita = "0.8"
webkit2gtk = "2.0.1"
tokio      = { version = "1", features = ["rt-multi-thread"] }
serde_json = "1"
